### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by soyaextract** [soyaextract/messageinasoyjak#1]
To do:
- [ ] dynamically add decode buttons when new posts appear
- [ ] file type sanity checking
- [ ] max message length checking
- [x] encode buttons and text input box next to file upload (7b38436bd13e3d9b7b60599146349116aab579be)
- [ ] post fused image directly instead of having to Save As
- [ ] make decode button use the page's css
- [ ] transparent png support
- [ ] unicode support
